services:
  postgres:
    image: postgres:16
    container_name: hear-me-out-postgres
    environment:
      POSTGRES_DB: hear_me_out
      POSTGRES_USER: hear_me_out_user
      POSTGRES_PASSWORD: hear_me_out_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
